### ISSUE TITLE
import error: 'modes' is not exported from '@mapbox/mapbox-gl-draw'

### ISSUE THREAD

**Issue by chuikoffru** [urbica/react-map-gl-draw#17]
Hey! I installed your tool like at docs:
`npm i mapbox-gl @mapbox/mapbox-gl-draw @urbica/react-map-gl @urbica/react-map-gl-draw`
![Screenshot 2020-07-15 at 10 50 52](https://user-images.githubusercontent.com/8284619/87483924-0ed6d180-c689-11ea-93b1-ae4770ac5d32.png)

But When I created a component, i've got an error:
![Screenshot 2020-07-15 at 10 56 17](https://user-images.githubusercontent.com/8284619/87484255-d4216900-c689-11ea-80d3-72531a6a7fb4.png)

My Component
![Screenshot 2020-07-15 at 10 53 43](https://user-images.githubusercontent.com/8284619/87484086-75f48600-c689-11ea-8a7e-7a819b83a628.png)

**Comment by braco** [comment]
Looks like it's because this library is out of date, go back to an older version of gl-draw:

`npm install --save @mapbox/mapbox-gl-draw@1.1.x`

**Comment by homerokzam** [comment]
Any update forecast?

Thanks

**Comment by danielpza** [comment]
I'm also having this issue, I downgraded to v1.1.x but now the icons don't show:

![image](https://user-images.githubusercontent.com/17787042/94076383-f262be00-fdca-11ea-9360-fdca4ad10ee8.png)
