### ISSUE TITLE
Map doesnt catch click when drawing (polygon) on map

### ISSUE THREAD

**Issue by daniela-green** [urbica/react-map-gl-draw#23]
When i draw a polygon on map, i want to be able to also click the map.
But my on click event of the map is not fired when polygon is drawn.
How can i get the map (and its layers) to be interactive at this point?

Thanks!

**Comment by daniela-green** [comment]
Basically what i want to do is to click the circle layer inside the polygon. 
Until now i did it via onClick of the MapGL, but maybe theres another way to achieve that?

**Comment by daniela-green** [comment]
Closing this as i understood the issue by myself.
The map is not interactive when  mode is in `EditingMode` or in `DrawPolygonMode`.
Changing the mode to `null` after polygon is added, makes the map interactive again.

**Comment by dudio92** [comment]
Thanks for that.
